Test API Key rzp_test_RsdlRNaJkGTirL
Test Key Secret O973p9ZVOQJtEJsHzuiqJml1

supabase secrets set RAZORPAY_KEY_ID=rzp_test_RsdlRNaJkGTirL
supabase secrets set RAZORPAY_KEY_SECRET=O973p9ZVOQJtEJsHzuiqJml1




create type public.order_status as enum ('pending','shipped','delivered','cancelled');
create type public.payment_status as enum ('pending','requires_action','paid','failed','refunded');

-- =========
-- PUBLIC LOOKUP TABLES
-- =========

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  image text,
  count integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  subtitle text,
  price integer not null,
  original_price integer,
  image text not null,
  category_id bigint not null references public.categories(id) on delete restrict,
  rating numeric(2,1) default 0,
  reviews integer default 0,
  in_stock boolean default true,
  featured boolean default false,
  is_new boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index idx_products_category_id on public.products(category_id);
create index idx_products_featured on public.products(featured);

create table public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image text not null,
  alt text,
  sort_order integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- =========
-- USERS / PROFILES
-- =========

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  avatar text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- =========
-- ADDRESSES
-- =========

create table public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  label text,
  full_name text,
  phone text,
  line1 text not null,
  line2 text,
  city text not null,
  state text not null,
  postal_code text not null,
  country text not null default 'India',
  is_default boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- =========
-- CARTS
-- =========

create table public.carts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete cascade,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.cart_items (
  id bigint generated by default as identity primary key,
  cart_id uuid not null references public.carts(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null check (quantity > 0),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (cart_id, product_id)
);

-- =========
-- ORDERS
-- =========

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete set null,
  status public.order_status not null default 'pending',
  payment_status public.payment_status not null default 'pending',
  total_amount integer not null,
  currency text not null default 'INR',
  stripe_payment_intent_id text,
  shipping_address_id bigint references public.addresses(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index idx_orders_user_id on public.orders(user_id);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null check (quantity > 0),
  unit_price integer not null,
  subtotal integer not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index idx_order_items_order_id on public.order_items(order_id);

-- =========
-- REVIEWS
-- =========

create table public.product_reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  title text,
  body text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (product_id, user_id)
);

-- =========
-- WISHLIST
-- =========

create table public.wishlist_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, product_id)
);

-- =========
-- NEWSLETTER
-- =========

create table public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);



-- POLICIES

alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.product_images enable row level security;

create policy "Public read products"
  on public.products
  for select
  using (true);

create policy "Public read categories"
  on public.categories
  for select
  using (true);

create policy "Public read product images"
  on public.product_images
  for select
  using (true);

-- PROFILES
alter table public.profiles enable row level security;

create policy "Users can view their own profile"
  on public.profiles
  for select
  using (auth.uid() = id);

create policy "Users can update their own profile"
  on public.profiles
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- ADDRESSES
alter table public.addresses enable row level security;

create policy "Users manage own addresses"
  on public.addresses
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- CARTS
alter table public.carts enable row level security;

create policy "Users manage their cart"
  on public.carts
  for all
  using (user_id is null or auth.uid() = user_id)
  with check (user_id is null or auth.uid() = user_id);

alter table public.cart_items enable row level security;

create policy "Users manage items of their cart"
  on public.cart_items
  for all
  using (
    exists (
      select 1 from public.carts c
      where c.id = cart_id
        and (c.user_id is null or c.user_id = auth.uid())
    )
  )
  with check (
    exists (
      select 1 from public.carts c
      where c.id = cart_id
        and (c.user_id is null or c.user_id = auth.uid())
    )
  );

-- ORDERS
alter table public.orders enable row level security;

create policy "Users see their own orders"
  on public.orders
  for select
  using (auth.uid() = user_id);

create policy "Users create own orders"
  on public.orders
  for insert
  with check (auth.uid() = user_id);

alter table public.order_items enable row level security;

create policy "Order items visible through own orders"
  on public.order_items
  for select
  using (
    exists (
      select 1 from public.orders o
      where o.id = order_id
        and o.user_id = auth.uid()
    )
  );

-- REVIEWS
alter table public.product_reviews enable row level security;

create policy "Users manage own reviews"
  on public.product_reviews
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- WISHLIST
alter table public.wishlist_items enable row level security;

create policy "Users manage own wishlist"
  on public.wishlist_items
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- NEWSLETTER (public can add; only server should read in production)
alter table public.newsletter_subscribers enable row level security;

create policy "Anyone can subscribe"
  on public.newsletter_subscribers
  for insert
  with check (true);

create policy "Only service role can read subscribers"
  on public.newsletter_subscribers
  for select
  using (auth.role() = 'service_role');


alright now we have to make that checkout page connected properly to our site and all, if you wanna want and check any file then just ask me

and tell me everything to do to do this step by step


CREATE OR REPLACE FUNCTION public.create_order_with_validation(p_user_id uuid, p_items jsonb, p_shipping_address_id bigint, p_payment_method text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_order_id uuid;
  v_total integer := 0;
  v_item jsonb;
  v_product_price integer;
  v_payment_status public.payment_status;
BEGIN
  -- 🔐 Secure search path
  PERFORM set_config('search_path', 'public', true);

  -- Determine payment status
  v_payment_status :=
    CASE
      WHEN p_payment_method = 'cod'
        THEN 'paid'::public.payment_status
      ELSE 'pending'::public.payment_status
    END;

  -- Calculate total securely from DB prices
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    SELECT price
    INTO v_product_price
    FROM public.products
    WHERE id = (v_item->>'product_id')::bigint;

    IF v_product_price IS NULL THEN
      RAISE EXCEPTION 'Invalid product id %', v_item->>'product_id';
    END IF;

    v_total :=
      v_total + (v_product_price * (v_item->>'quantity')::integer);
  END LOOP;

  -- Insert order
  INSERT INTO public.orders (
    user_id,
    total_amount,
    currency,
    status,
    payment_status,
    shipping_address_id
  )
  VALUES (
    p_user_id,
    v_total,
    'INR',
    'pending'::public.order_status,
    v_payment_status,
    p_shipping_address_id
  )
  RETURNING id INTO v_order_id;

  -- Insert order items
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    SELECT price
    INTO v_product_price
    FROM public.products
    WHERE id = (v_item->>'product_id')::bigint;

    INSERT INTO public.order_items (
      order_id,
      product_id,
      quantity,
      unit_price,
      subtotal
    )
    VALUES (
      v_order_id,
      (v_item->>'product_id')::bigint,
      (v_item->>'quantity')::integer,
      v_product_price,
      v_product_price * (v_item->>'quantity')::integer
    );
  END LOOP;

  RETURN v_order_id;
END;
$function$


